# Generated by Django 4.1.4 on 2022-12-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='foods/'),
        ),
    ]
